package eu.a2a.salesgate.pratiche.bean;

import java.util.Date;

import eu.a2a.salesgate.bean.CodDescBean;

/**
 * AvanzamentoFlussi generated by hbm2java
 */
public class AvanzamentoFlussi extends CodDescBean {

  private static final long serialVersionUID = 5816805604622063849L;
  private String fkPratica;
  private String fkLavori;
  private String codServizio;
  private String commodity;
  private String codFlusso;
  private String stato;
  private String flagStato;
  private int numReinvio;
  private Date created;
  private Date lastUpdated;

  public AvanzamentoFlussi() {
  }

  public AvanzamentoFlussi(String fkPratica) {
    this.fkPratica = fkPratica;
  }

  public AvanzamentoFlussi(String fkPratica, String fkLavori, String codServizio, String commodity, String codFlusso,
      String stato, String flagStato, int numReinvio, Date created, Date lastUpdated) {
    this.fkPratica = fkPratica;
    this.fkLavori = fkLavori;
    this.codServizio = codServizio;
    this.commodity = commodity;
    this.codFlusso = codFlusso;
    this.stato = stato;
    this.flagStato = flagStato;
    this.numReinvio = numReinvio;
    this.created = created;
    this.lastUpdated = lastUpdated;
  }

  public String getFkPratica() {
    return this.fkPratica;
  }

  public void setFkPratica(String fkPratica) {
    this.fkPratica = fkPratica;
  }

  public String getFkLavori() {
    return this.fkLavori;
  }

  public void setFkLavori(String fkLavori) {
    this.fkLavori = fkLavori;
  }

  public String getCodServizio() {
    return this.codServizio;
  }

  public void setCodServizio(String codServizio) {
    this.codServizio = codServizio;
  }

  public String getCommodity() {
    return this.commodity;
  }

  public void setCommodity(String commodity) {
    this.commodity = commodity;
  }

  public String getCodFlusso() {
    return this.codFlusso;
  }

  public void setCodFlusso(String codFlusso) {
    this.codFlusso = codFlusso;
  }

  public String getStato() {
    return this.stato;
  }

  public void setStato(String stato) {
    this.stato = stato;
  }

  public String getFlagStato() {
    return this.flagStato;
  }

  public void setFlagStato(String flagStato) {
    this.flagStato = flagStato;
  }

  public int getNumReinvio() {
    return this.numReinvio;
  }

  public void setNumReinvio(int numReinvio) {
    this.numReinvio = numReinvio;
  }

  public Date getCreated() {
    return this.created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public Date getLastUpdated() {
    return this.lastUpdated;
  }

  public void setLastUpdated(Date lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

}
