package eu.a2a.salesgate.pratiche.ele.bean;

// Generated 27-set-2013 11.36.08 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import eu.a2a.salesgate.bean.CodDescBean;

/**
 * LavoriGasXDatiTecnici generated by hbm2java
 */
public class LavoriEleXDatiTecnici extends CodDescBean {

  private static final long serialVersionUID = 1L;
  private String fkLavoriEle;
  private String potenza;
  private String fase;
  private String tensione;
  private BigDecimal numeroPunti;

  public LavoriEleXDatiTecnici() {
  }

  public LavoriEleXDatiTecnici(String id) {
    super(id);
  }

  public String getFkLavoriEle() {
    return fkLavoriEle;
  }

  public void setFkLavoriEle(String fkLavoriEle) {
    this.fkLavoriEle = fkLavoriEle;
  }

  public String getPotenza() {
    return potenza;
  }

  public void setPotenza(String potenza) {
    this.potenza = potenza;
  }

  public String getFase() {
    return fase;
  }

  public void setFase(String fase) {
    this.fase = fase;
  }

  public String getTensione() {
    return tensione;
  }

  public void setTensione(String tensione) {
    this.tensione = tensione;
  }

  public BigDecimal getNumeroPunti() {
    return numeroPunti;
  }

  public void setNumeroPunti(BigDecimal numeroPunti) {
    this.numeroPunti = numeroPunti;
  }

}
