package eu.a2a.salesgate.pratiche.gas.bean;

// Generated 27-set-2013 11.36.08 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * LavoriGasXPreventivi generated by hbm2java
 */
public class LavoriGasXPreventivi implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private LavoriGasXCliente lavoriGasXCliente;
	private LavoriGas lavoriGas;
	private String esito;
	private Date dataRichPrev;
	private Date dataValPrev;
	private String forfait;
	private String modAccPrev;
	private String oneriManodopera;
	private String oneriMat;
	private String oneriTerzi;
	private String portataEsist;
	private String portataNew;
	private String pressioneNew;
	private String speseGen;
	private String tipoGas;
	private String tot;
	private String totImponibile;
	private String totIva;
	private String variazioneImporti;
	private String autDistr;
	private String privacy;
	private String altriOneri1;
	private String descAltriOneri1;
	private String altriOneri2;
	private String descAltriOneri2;
	private Date created;
	private Date lastUpdated;

	public LavoriGasXPreventivi() {
	}

	public LavoriGasXPreventivi(BigDecimal id) {
		this.id = id;
	}

	public LavoriGasXPreventivi(BigDecimal id,
			LavoriGasXCliente lavoriGasXCliente, LavoriGas lavoriGas,
			String esito, Date dataRichPrev, Date dataValPrev, String forfait,
			String modAccPrev, String oneriManodopera, String oneriMat,
			String oneriTerzi, String portataEsist, String portataNew,
			String pressioneNew, String speseGen, String tipoGas, String tot,
			String totImponibile, String totIva, String variazioneImporti,
			String autDistr, String privacy, String altriOneri1,
			String descAltriOneri1, String altriOneri2, String descAltriOneri2,
			Date created, Date lastUpdated) {
		this.id = id;
		this.lavoriGasXCliente = lavoriGasXCliente;
		this.lavoriGas = lavoriGas;
		this.esito = esito;
		this.dataRichPrev = dataRichPrev;
		this.dataValPrev = dataValPrev;
		this.forfait = forfait;
		this.modAccPrev = modAccPrev;
		this.oneriManodopera = oneriManodopera;
		this.oneriMat = oneriMat;
		this.oneriTerzi = oneriTerzi;
		this.portataEsist = portataEsist;
		this.portataNew = portataNew;
		this.pressioneNew = pressioneNew;
		this.speseGen = speseGen;
		this.tipoGas = tipoGas;
		this.tot = tot;
		this.totImponibile = totImponibile;
		this.totIva = totIva;
		this.variazioneImporti = variazioneImporti;
		this.autDistr = autDistr;
		this.privacy = privacy;
		this.altriOneri1 = altriOneri1;
		this.descAltriOneri1 = descAltriOneri1;
		this.altriOneri2 = altriOneri2;
		this.descAltriOneri2 = descAltriOneri2;
		this.created = created;
		this.lastUpdated = lastUpdated;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public LavoriGasXCliente getLavoriGasXCliente() {
		return this.lavoriGasXCliente;
	}

	public void setLavoriGasXCliente(LavoriGasXCliente lavoriGasXCliente) {
		this.lavoriGasXCliente = lavoriGasXCliente;
	}

	public LavoriGas getLavoriGas() {
		return this.lavoriGas;
	}

	public void setLavoriGas(LavoriGas lavoriGas) {
		this.lavoriGas = lavoriGas;
	}

	public String getEsito() {
		return this.esito;
	}

	public void setEsito(String esito) {
		this.esito = esito;
	}

	public Date getDataRichPrev() {
		return this.dataRichPrev;
	}

	public void setDataRichPrev(Date dataRichPrev) {
		this.dataRichPrev = dataRichPrev;
	}

	public Date getDataValPrev() {
		return this.dataValPrev;
	}

	public void setDataValPrev(Date dataValPrev) {
		this.dataValPrev = dataValPrev;
	}

	public String getForfait() {
		return this.forfait;
	}

	public void setForfait(String forfait) {
		this.forfait = forfait;
	}

	public String getModAccPrev() {
		return this.modAccPrev;
	}

	public void setModAccPrev(String modAccPrev) {
		this.modAccPrev = modAccPrev;
	}

	public String getOneriManodopera() {
		return this.oneriManodopera;
	}

	public void setOneriManodopera(String oneriManodopera) {
		this.oneriManodopera = oneriManodopera;
	}

	public String getOneriMat() {
		return this.oneriMat;
	}

	public void setOneriMat(String oneriMat) {
		this.oneriMat = oneriMat;
	}

	public String getOneriTerzi() {
		return this.oneriTerzi;
	}

	public void setOneriTerzi(String oneriTerzi) {
		this.oneriTerzi = oneriTerzi;
	}

	public String getPortataEsist() {
		return this.portataEsist;
	}

	public void setPortataEsist(String portataEsist) {
		this.portataEsist = portataEsist;
	}

	public String getPortataNew() {
		return this.portataNew;
	}

	public void setPortataNew(String portataNew) {
		this.portataNew = portataNew;
	}

	public String getPressioneNew() {
		return this.pressioneNew;
	}

	public void setPressioneNew(String pressioneNew) {
		this.pressioneNew = pressioneNew;
	}

	public String getSpeseGen() {
		return this.speseGen;
	}

	public void setSpeseGen(String speseGen) {
		this.speseGen = speseGen;
	}

	public String getTipoGas() {
		return this.tipoGas;
	}

	public void setTipoGas(String tipoGas) {
		this.tipoGas = tipoGas;
	}

	public String getTot() {
		return this.tot;
	}

	public void setTot(String tot) {
		this.tot = tot;
	}

	public String getTotImponibile() {
		return this.totImponibile;
	}

	public void setTotImponibile(String totImponibile) {
		this.totImponibile = totImponibile;
	}

	public String getTotIva() {
		return this.totIva;
	}

	public void setTotIva(String totIva) {
		this.totIva = totIva;
	}

	public String getVariazioneImporti() {
		return this.variazioneImporti;
	}

	public void setVariazioneImporti(String variazioneImporti) {
		this.variazioneImporti = variazioneImporti;
	}

	public String getAutDistr() {
		return this.autDistr;
	}

	public void setAutDistr(String autDistr) {
		this.autDistr = autDistr;
	}

	public String getPrivacy() {
		return this.privacy;
	}

	public void setPrivacy(String privacy) {
		this.privacy = privacy;
	}

	public String getAltriOneri1() {
		return this.altriOneri1;
	}

	public void setAltriOneri1(String altriOneri1) {
		this.altriOneri1 = altriOneri1;
	}

	public String getDescAltriOneri1() {
		return this.descAltriOneri1;
	}

	public void setDescAltriOneri1(String descAltriOneri1) {
		this.descAltriOneri1 = descAltriOneri1;
	}

	public String getAltriOneri2() {
		return this.altriOneri2;
	}

	public void setAltriOneri2(String altriOneri2) {
		this.altriOneri2 = altriOneri2;
	}

	public String getDescAltriOneri2() {
		return this.descAltriOneri2;
	}

	public void setDescAltriOneri2(String descAltriOneri2) {
		this.descAltriOneri2 = descAltriOneri2;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
